x=13
try:
  print(x)
except Exception as err:
  print(str(err))
